spring:
  application:
    name: consumer-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

  elasticsearch:
    uris: http://localhost:9200
    
logging:
  level:
    root: INFO
    com.guberan: DEBUG